--PART A

SELECT * FROM DEPOSIT_DETAIL;
--1
ALTER TABLE DEPOSIT ADD CITY VARCHAR(20),
                        PINCODE INT;
--2
ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35);
--3
ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT;
--4
SP_RENAME 'DEPOSIT_DETAIL.ACTNO', ANO;
--5
ALTER TABLE DEPOSIT_DETAIL DROP COLUMN CITY;
--6
SP_RENAME DEPOSIT,DEPOSIT_DETAIL;

--PART B
--1
SP_RENAME 'DEPOSIT_DETAIL.ADATE', AOPENDATE;
--2
ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPENDATE;
--3
SP_RENAME 'DEPOSIT_DETAIL.CNAME', CUSTOMERNAME;

--PART C
CREATE TABLE STUDENT_DETAIL
( ENROLLMENT_NO VARCHAR(20),
  NAME VARCHAR(25),
  CPI DECIMAL(5,2),
  BIRTHDATE DATETIME);

SELECT * FROM STUDENT_DETAIL; 
--1
ALTER TABLE STUDENT_DETAIL ADD CITY VARCHAR(20) NOT NULL,
                               BACKLOG INT;
--2
ALTER TABLE STUDENT_DETAIL ALTER COLUMN NAME VARCHAR(35);
--3
ALTER TABLE STUDENT_DETAIL ALTER COLUMN CPI INT;
--4
SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO', ENO;
--5
ALTER TABLE STUDENT_DETAIL DROP COLUMN CITY;
--6
SP_RENAME STUDENT_DETAIL,STUDENT_MASTER;

--DELETE,TRUNCATE,DROP OPERATION
--PART A
--1
DELETE FROM DEPOSIT_DETAIL WHERE AMOUNT>4000;
--2
DELETE FROM DEPOSIT_DETAIL WHERE BNAME='CHANDI';
--3
DELETE FROM DEPOSIT_DETAIL WHERE ANO>105;
--4
TRUNCATE TABLE DEPOSIT_DETAIL;
--5
DROP TABLE DEPOSIT_DETAIL;

--PART B
CREATE TABLE EMPLOYEE_MASTER
( EMPNO INT,
  EMPNAME VARCHAR(25),
  JOININGDATE DATETIME,
  SALARY DECIMAL(8,2),
  CITY VARCHAR(20));

SELECT * FROM EMPLOYEE_MASTER;

--1
DELETE FROM EMPLOYEE_MASTER WHERE SALARY>14000 OR SALARY=14000;
--2
DELETE FROM EMPLOYEE_MASTER WHERE CITY='RAJKOT';
--3
DELETE FROM EMPLOYEE_MASTER WHERE JOININGDATE>'01-01-2007';
--4
DELETE FROM EMPLOYEE_MASTER WHERE JOININGDATE IS NULL AND EMPNAME IS NOT NULL;
--5
DELETE FROM EMPLOYEE_MASTER WHERE SALARY=0.5*20000;
--6
DELETE FROM EMPLOYEE_MASTER WHERE CITY IS NOT NULL;
--7
DELETE FROM EMPLOYEE_MASTER;
--8
DROP TABLE EMPLOYEE_MASTER;