CREATE TABLE SALES_DATA
(REGION VARCHAR(50),
 PRODUCT VARCHAR(10),
 SALES_AMOUNT INT,
 YEAR INT);

INSERT INTO SALES_DATA VALUES('NORTH AMERICA','WATCH',1500,2023);
INSERT INTO SALES_DATA VALUES('EUROPE','MOBILE',1200,2023);
INSERT INTO SALES_DATA VALUES('ASIA','WATCH',1800,2023);
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','TV',900,2024);
INSERT INTO SALES_DATA VALUES('EUROPE','WATCH',2000,2024);
INSERT INTO SALES_DATA VALUES('ASIA','MOBILE',1000,2024);
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','MOBILE',1600,2023);
INSERT INTO SALES_DATA VALUES('EUROPE','TV',1500,2023);
INSERT INTO SALES_DATA VALUES('ASIA','TV',1100,2024);
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','WATCH',1700,2024);

SELECT * FROM SALES_DATA;

--PART-A
--1
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM SALES_DATA GROUP BY REGION;
--2
SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVG_SALES FROM SALES_DATA GROUP BY PRODUCT;
--3
SELECT YEAR,MAX(SALES_AMOUNT) AS MAX_SALES FROM SALES_DATA GROUP BY YEAR;
--4
SELECT REGION,YEAR,MIN(SALES_AMOUNT) AS MIN_SALES FROM SALES_DATA GROUP BY REGION,YEAR;
--5
SELECT REGION,COUNT(SALES_AMOUNT) AS COUNT_SALES FROM SALES_DATA GROUP BY REGION;
--6
SELECT YEAR,PRODUCT,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM SALES_DATA GROUP BY YEAR,PRODUCT;
--7
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM SALES_DATA GROUP BY REGION HAVING SUM(SALES_AMOUNT)>5000;
--8
SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVG_SALES FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT)<10000;
--9
SELECT YEAR,MAX(SALES_AMOUNT) AS MAX_SALES FROM SALES_DATA GROUP BY YEAR HAVING MAX(SALES_AMOUNT)>500;
--10
SELECT COUNT(DISTINCT PRODUCT) AS DISTINCT_PRODUCT FROM SALES_DATA HAVING COUNT(DISTINCT PRODUCT)>=3;
--11
SELECT YEAR,MIN(SALES_AMOUNT) AS MIN_SALES FROM SALES_DATA HAVING MIN(SALES_AMOUNT)<1000;
--12
SELECT REGION,SUM(SALES_AMOUNT) AS T0TAL_SALES FROM SALES_DATA WHERE YEAR=2023 GROUP BY REGION ORDER BY SUM(SALES_AMOUNT);

--PART-B
--1
SELECT YEAR,REGION,COUNT(*) FROM SALES_DATA GROUP BY YEAR,REGION ORDER BY YEAR,REGION;
--2
SELECT REGION,MAX(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION HAVING MAX(SALES_AMOUNT)>1000 ORDER BY REGION;
--3
SELECT YEAR,SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR HAVING SUM(SALES_AMOUNT)<1000 ORDER BY YEAR DESC;
--4
SELECT TOP 3 REGION,SUM(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR=2024 GROUP BY REGION;

--PART-C
--1
SELECT PRODUCT,AVG(SALES_AMOUNT) FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000 ORDER BY PRODUCT;
--2
SELECT YEAR,COUNT(REGION) FROM SALES_DATA GROUP BY YEAR HAVING COUNT(REGION)>5;
--3
SELECT REGION,AVG(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR=2023 GROUP BY REGION HAVING AVG(SALES_AMOUNT)>1500 ORDER BY AVG(SALES_AMOUNT) DESC;
--4
SELECT REGION,COUNT(PRODUCT),PRODUCT FROM SALES_DATA GROUP BY REGION,PRODUCT HAVING COUNT(PRODUCT)>1;
--5
SELECT REGION,MAX(SALES_AMOUNT)AS MAX_SALES FROM SALES_DATA GROUP BY REGION;
