--PART A

CREATE TABLE CRICKET
( NAME VARCHAR(50),
  CITY VARCHAR(20),
  AGE INT);

INSERT INTO CRICKET VALUES('SACHIN TENDULKAR','MUMBAI',30);
INSERT INTO CRICKET VALUES('RAHUL DRAVID','BOMBAY',35);
INSERT INTO CRICKET VALUES('M.S. DHONI','JHARKHAND',31);
INSERT INTO CRICKET VALUES('SURESH RAINA','GUJARAT',30);

SELECT * FROM CRICKET;

--1
SELECT * INTO WORLDCUP FROM CRICKET;
--2
SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1=0;
--3
SELECT * INTO IPL FROM CRICKET WHERE 1=0;

--PART B

CREATE TABLE EMPLOYEE
( NAME VARCHAR(50),
  CITY VARCHAR(20),
  AGE INT);

INSERT INTO EMPLOYEE VALUES('JAY PATEL','RAJKOT',30);
INSERT INTO EMPLOYEE VALUES('RAHUL DAVE','BARODA',35);
INSERT INTO EMPLOYEE VALUES('JEET PATEL','SURAT',31);
INSERT INTO EMPLOYEE VALUES('VIJAY RAVAL','RAJKOT',30);
SELECT * FROM EMPLOYEE;

--1
SELECT * INTO EMPLOYEE_DETAIL FROM EMPLOYEE;
--2
SELECT NAME,CITY INTO EMPLOYEE_DATA FROM EMPLOYEE WHERE 1=0;
--3
SELECT * INTO EMPLOYEE_INFO FROM EMPLOYEE WHERE 1=0;
SELECT * FROM EMPLOYEE_INFO;
--PART C
--1
INSERT INTO  EMPLOYEE_INFO(NAME,CITY,AGE)
SELECT NAME,CITY,AGE FROM EMPLOYEE
WHERE CITY='RAJKOT';
--2
INSERT INTO  EMPLOYEE_INFO(NAME,CITY,AGE)
SELECT NAME,CITY,AGE FROM EMPLOYEE
WHERE AGE>32;


--UPDATE
--PART A
SELECT * FROM DEPOSIT;
--1
UPDATE DEPOSIT SET AMOUNT=5000 WHERE AMOUNT=3000;
--2
UPDATE BORROW SET BNAME='C.G. ROAD' WHERE CNAME='ANIL';
--3
UPDATE DEPOSIT SET ACTNO=111,AMOUNT=5000 WHERE CNAME='SANDIP';
--4
UPDATE DEPOSIT SET AMOUNT=7000 WHERE CNAME='KRANTI';
--5
UPDATE BRANCH SET BNAME='ANDHERI WEST' WHERE BNAME='ANDHERI';
--6
UPDATE DEPOSIT SET BNAME='NEHRU PLACE' WHERE CNAME='MEHUL';
--7
UPDATE DEPOSIT SET AMOUNT=5000 WHERE ACTNO>103 OR ACTNO<107;
--8
UPDATE DEPOSIT SET ADATE='01-04-1995' WHERE CNAME='ANIL';
--9
UPDATE DEPOSIT SET AMOUNT=10000 WHERE CNAME='MINU';
--10
UPDATE DEPOSIT SET AMOUNT=5000,ADATE='01-04-1996' WHERE CNAME='PRAMOD';

--PART B
--1
UPDATE BORROW SET AMOUNT=(AMOUNT*0.1)+AMOUNT;
--2
UPDATE DEPOSIT SET AMOUNT=(AMOUNT*0.2)+AMOUNT;

--PART C
SELECT * FROM BORROW;
--1
UPDATE BORROW SET LOANNO=NULL WHERE LOANNO=321;
--2
UPDATE BORROW SET BNAME=NULL WHERE CNAME='KRANTI';
--3
SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL;
--4
SELECT CNAME FROM BORROW WHERE BNAME IS NOT NULL;
--5
UPDATE BORROW SET LOANNO=5000,BNAME='VRCE',CNAME='DARSHAN' WHERE LOANNO=481;
--6
UPDATE DEPOSIT SET ADATE='01-01-2021' WHERE AMOUNT<2000;
--7
UPDATE DEPOSIT SET ADATE=NULL,BNAME='ANDHERI' WHERE ACTNO=110;